name: Package and Release to GitLab

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  package-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Setup jq
      run: |
        # 确保 jq 已安装
        sudo apt-get update
        sudo apt-get install -y jq
      
    - name: Create ZIP package
      run: |
        cd Better-Names-for-7FA4
        zip -r ../Better-Names-for-7FA4-${{ github.ref_name }}.zip .
        
    - name: Create Release in GitLab
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        GITLAB_URL: "http://jx.7fa4.cn:9080"
      run: |
        # 设置变量
        TAG_NAME=${GITHUB_REF#refs/tags/}
        ZIP_FILE="Better-Names-for-7FA4-$TAG_NAME.zip"
        PROJECT_ID="wsh%2Ftest"
        
        echo "Creating release $TAG_NAME in GitLab..."
        
        # 1. 首先上传文件到 GitLab
        UPLOAD_RESPONSE=$(curl --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
          --form "file=@$ZIP_FILE" \
          "$GITLAB_URL/api/v4/projects/$PROJECT_ID/uploads" -s)
        
        echo "Upload response: $UPLOAD_RESPONSE"
        
        # 提取上传文件的 markdown 链接和 URL
        UPLOAD_MARKDOWN=$(echo "$UPLOAD_RESPONSE" | jq -r '.markdown')
        UPLOAD_URL=$(echo "$UPLOAD_RESPONSE" | jq -r '.url')
        
        # 构建完整的文件 URL
        FULL_FILE_URL="$GITLAB_URL$UPLOAD_URL"
        
        # 2. 使用 jq 构建 JSON 数据
        RELEASE_JSON=$(jq -n \
          --arg name "Better Names for 7FA4 $TAG_NAME" \
          --arg tag "$TAG_NAME" \
          --arg desc "Automated release from GitHub Actions. Download: $UPLOAD_MARKDOWN" \
          --arg url "$FULL_FILE_URL" \
          --arg file_name "Better-Names-for-7FA4-$TAG_NAME.zip" \
          '{
            name: $name,
            tag_name: $tag,
            description: $desc,
            assets: {
              links: [
                {
                  name: $file_name,
                  url: $url,
                  link_type: "package"
                }
              ]
            }
          }')
        
        echo "Release JSON: $RELEASE_JSON"
        
        # 3. 创建 release
        curl --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
          --header "Content-Type: application/json" \
          --data "$RELEASE_JSON" \
          "$GITLAB_URL/api/v4/projects/$PROJECT_ID/releases"
        
        echo "Release created successfully!"